### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by ubcent** [koutsenko/gb-js2016#1]
1. Служебные файлы среды разработки (.vscode) не должны попадать в репо, их нужно добавлять в .gitignore.
2. По оформлению. Желательно отступы сделать в 2 пробела, а не в 4, тк в JS часто встречаются длинные выражения, которые не влезают в строку.

**Comment by ubcent** [comment]
3. Это не реализация в парадигме ООП, так что второе ДЗ сделать все-таки придется :-)

**Comment by koutsenko** [comment]
Сделал .gitignore, его содержимое
```
.gitignore
.vscode/
```

Отступы переформатировал.

**Comment by ubcent** [comment]
Кстати .gitignore  не надо запиливать в .gitignore, он нужен в репозитарии

**Comment by koutsenko** [comment]
Видел мнение, что у разных разработчиков может быть разная среда и соответственно свой .gitignore у каждого...

**Comment by ubcent** [comment]
Единственное, что может различаться у разработчиков одного проекта - среда разработки, все остальное - общее. Просто добавляются игноры всего. Кроме того часто в проектах участвуют не очень опытные разработчики, которые не знаю что такое gitignore:-) Так же при необходимости можно добавлять игнор по шаблону, чаще всего для служебных файлов IDE так и делают, большинство начинаются на "."

**Comment by ubcent** [comment]
Разумеется я имею ввиду не содержимое файлов, а их наличие:-)

**Comment by koutsenko** [comment]
Спасибо за подсказку, закоммитил

**Comment by koutsenko** [comment]
Переделал код в объектный. Теперь можно создавать сколько угодно экземпляров таблиц. 
Нюансы:
1) Это в рамках 1го задания, т.к. ООП на мой взгляд здесь нет, т.к. нет наследования.
2) Пока не придумал что делать с клавишами, если создается более 1-й шахматки...

**Comment by koutsenko** [comment]
@ubcent , теперь реализовано и наследование. От замыканий отказался, потому что сымитированные с их помощью приватные члены базового класса в ES3\ES5 нельзя переопределить в потомке - сначала наткнулся на это сам, потом вычитал и подтверждение у Кантора. У меня к Вам вопрос:

"Радужная таблица" [https://github.com/koutsenko/gb-js2016/blob/master/lesson1/js/tableRainbow.js](tableRainbow.js) наследуется от базовой таблицы в table.js. Скажите пожалуйста, а как в ES3 выглядела бы строка копирования прототипа? Мне пришлось сделать в стиле ES5:

`Object.setPrototypeOf(TableRainbow.prototype, Table.prototype);`

А по-другому можно?
